version: '3.4'

services:
  malware-service:
    environment:
      WAIT_HOSTS: ${MALWARE_SERVICE_WAIT_HOSTS}
      Mongo__ConnectionString: ${MONGO_HOST}
      Mongo__MassTransitDatabase: ${MONGO_MASSTRANSIT_DATABASE_NAME}
      EventBus__IPAddress: ${RABBITMQ_HOST}
      EventBus__UserName: ${RABBITMQ_DEFAULT_USER}
      EventBus__Password: ${RABBITMQ_DEFAULT_PASS}
      EventBus__PortNumber: ${RABBITMQ_DEFAULT_PORT}
      ClamAVServer__URL: ${ClamAV_Server}
      ClamAVServer__Port: ${ClamAV_Port}
    networks:
     - netije-network
    command: sh -c "/wait && dotnet MalwareService.dll"

  clamAVServer:
    environment:
      MAX_FILE_SIZE: ${ClaimAV_MAX_FILE_SIZE}
      STREAM_MAX_LENGTH: ${ClaimAV_MAX_FILE_SIZE}
    volumes:
     - clamAV-data:/data/definitions
    networks: 
     - netije-network