version: '3.4'

services:
   postgresdb:
    container_name: postgresdb
    image: postgres:latest
    restart: always

   mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always

volumes:
  postgres-db-data:
  mongo-db-data: